import React, { Component } from 'react';

export default class Home extends Component {
  render(){
    return(
      <>
      <h1>Conteudoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      <h1>Conteudo</h1>
      </>
    )
  }
}
